<!doctype html><html lang="it"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#101827"><link rel="manifest" href="/manifest.json"><title>FVC Project</title><style>
:root{--bg:#101827;--panel:#172235;--line:#31415b;--gold:#d4af37;--text:#f6f7fb;--muted:#aebbd0}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font:15px system-ui,-apple-system,sans-serif}header,main,footer{max-width:900px;margin:auto;padding:20px}.hero{padding:36px 20px 28px;background:linear-gradient(140deg,#182942,#101827)}h1,h2,h3,p{margin-top:0}.eyebrow{color:var(--gold);font-size:12px;text-transform:uppercase;letter-spacing:.1em}.tiles,.grid,.news{display:grid;gap:12px}.tiles{grid-template-columns:repeat(3,1fr)}.tile,.card,.news article{background:var(--panel);border:1px solid var(--line);border-radius:14px;padding:15px}.tile{color:inherit;text-decoration:none;text-align:center}.news article{border-color:#806d2d}.news h4{color:var(--gold);margin:0 0 6px}.muted{color:var(--muted)}.toolbar{display:flex;gap:8px;flex-wrap:wrap;margin-bottom:14px}input,select,button{font:inherit;border-radius:9px;padding:10px;border:1px solid var(--line)}input,select{background:#0e1727;color:var(--text);flex:1}button{background:var(--gold);color:#111827;border:0;font-weight:700;cursor:pointer}.grid{grid-template-columns:repeat(auto-fill,minmax(190px,1fr))}.product img{width:100%;height:130px;object-fit:contain;border-radius:10px;background:white}.product h4{margin:10px 0 5px}.price{font-size:18px;color:var(--gold);font-weight:700}.rate{font-size:13px;color:var(--muted)}.plan{display:flex;justify-content:space-between;gap:12px;align-items:center}.clickable{cursor:pointer;transition:transform .12s,border-color .12s}.clickable:hover{transform:translateY(-2px);border-color:var(--gold)}.detail-backdrop{position:fixed;inset:0;background:rgba(0,0,0,.72);display:none;align-items:center;justify-content:center;padding:18px;z-index:1000}.detail-backdrop.open{display:flex}.detail-modal{width:min(620px,100%);max-height:90vh;overflow:auto;background:var(--panel);border:1px solid var(--line);border-radius:18px;padding:20px;box-shadow:0 20px 60px rgba(0,0,0,.45)}.detail-head{display:flex;justify-content:space-between;gap:12px;align-items:flex-start}.detail-close{background:transparent;color:var(--text);border:1px solid var(--line);padding:7px 11px}.detail-image{width:100%;max-height:300px;object-fit:contain;background:white;border-radius:12px;margin:14px 0}.detail-list{display:grid;gap:8px;margin:14px 0}.detail-row{display:flex;justify-content:space-between;gap:15px;padding:9px 0;border-bottom:1px solid var(--line)}.detail-row span:first-child{color:var(--muted)}.detail-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:16px}.detail-actions a{text-decoration:none}.qr{display:flex;gap:20px;align-items:center}.qr img{width:130px;background:white;padding:8px;border-radius:10px}@media(max-width:550px){.tiles{grid-template-columns:1fr}.qr{align-items:flex-start}.hero{padding-top:24px}.detail-modal{padding:16px}.detail-row{display:block}.detail-row span{display:block;margin-bottom:3px}}
</style></head><body><header class="hero"><p class="eyebrow">Telefonia e assistenza</p><h1 id="shop">FVC Project</h1><p class="muted">Catalogo, offerte e novità sempre aggiornati.</p><nav class="tiles"><a class="tile" href="#catalogo">Catalogo</a><a class="tile" href="#telefonia">Telefonia & Fibra</a><a class="tile" href="#offerte">Offerte</a></nav></header><main>
<section id="novita" hidden><p class="eyebrow">Appena aggiornato</p><h2>Novità</h2><div class="news" id="news"></div></section>
<section id="catalogo"><p class="eyebrow">Smartphone e accessori</p><h2>Catalogo</h2><div class="toolbar"><input id="search" type="search" placeholder="Cerca marca o modello"><select id="brand"><option value="">Tutte le marche</option></select></div><div class="grid" id="products"></div></section>
<section id="telefonia"><p class="eyebrow">Mobile e fibra</p><h2>Telefonia & Fibra</h2><div class="news" id="plans"></div></section>
<section id="offerte"><p class="eyebrow">Promozioni</p><h2>Offerte del mese</h2><div class="news" id="offers"></div></section>
<section class="qr"><img src="/api/qr" alt="QR code dell'app"><div><h2>Porta FVC sempre con te</h2><p class="muted">Inquadra il QR code per aprire l'app sul tuo smartphone.</p><button id="push">Attiva notifiche</button></div></section>
</main><footer><p class="muted" id="contacts"></p><p><a href="/admin.html" style="color:#aebbd0">Area riservata</a></p></footer>
<div id="detailBackdrop" class="detail-backdrop" role="dialog" aria-modal="true" aria-labelledby="detailTitle"><div class="detail-modal"><div class="detail-head"><div><p class="eyebrow" id="detailType">Dettaglio</p><h2 id="detailTitle"></h2></div><button class="detail-close" id="detailClose" aria-label="Chiudi">✕</button></div><div id="detailBody"></div></div></div>
<script>
let cfg={products:[],offers:[],plans:[],news:[]};
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function row(l,v){return v?`<div class="detail-row"><span>${esc(l)}</span><strong>${esc(v)}</strong></div>`:''}
function openDetail(type,item){$('detailType').textContent=type;$('detailTitle').textContent=item.name||item.title||'Dettaglio';let h='';
if(item.image)h+=`<img class="detail-image" src="${esc(item.image)}" alt="">`;
if(type==='Prodotto'){h+=`<div class="detail-list">${row('Marca',item.brand)}${row('Specifiche',item.spec)}${row('Prezzo',item.price)}${row('Disponibilità',item.stock?item.stock+' disponibili':'')}</div>`;if(item.installments?.length)h+='<h3>Rate</h3><div class="detail-list">'+item.installments.map(r=>row(r.months||'Rata',r.amount)).join('')+'</div>'}
else if(type==='Telefonia / Fibra'){h+=`<div class="detail-list">${row('Gestore',item.carrier)}${row('Tipo',item.type==='fibra'?'Fibra':'Mobile')}${row('Prezzo',item.price)}</div><p class="muted">${esc(item.details||'')}</p>`;if(item.file&&item.fileName)h+=`<div class="detail-actions"><a href="${esc(item.file)}" target="_blank" rel="noopener"><button>Apri ${esc(item.fileName)}</button></a></div>`}
else{h+=`<div class="detail-list">${row('Sconto',item.pct)}</div><p class="muted">${esc(item.description||item.desc||'')}</p>`}
$('detailBody').innerHTML=h;$('detailBackdrop').classList.add('open');document.body.style.overflow='hidden'}
function closeDetail(){$('detailBackdrop').classList.remove('open');document.body.style.overflow=''}
function render(){const q=$('search').value.toLowerCase(),b=$('brand').value,fp=cfg.products.filter(p=>`${p.name} ${p.brand}`.toLowerCase().includes(q)&&(!b||p.brand===b));
$('products').innerHTML=fp.map(p=>`<article class="card product clickable" data-kind="product" data-index="${cfg.products.indexOf(p)}" tabindex="0" role="button">${p.image?`<img src="${esc(p.image)}" alt="">`:''}<h4>${esc(p.name)}</h4><p class="muted">${esc(p.brand||'')} ${esc(p.spec||'')}</p><div class="price">${esc(p.price)}</div>${p.rate?`<div class="rate">A rate: ${esc(p.rate)}</div>`:''}<p class="muted">Tocca per vedere i dettagli</p></article>`).join('')||'<p class="muted">Nessun prodotto trovato.</p>';
$('plans').innerHTML=cfg.plans.map((p,i)=>`<article class="card plan clickable" data-kind="plan" data-index="${i}" tabindex="0" role="button"><div><b>${esc(p.name)}</b><p class="muted">${esc(p.details)}</p></div><b class="price">${esc(p.price)}</b></article>`).join('')||'<p class="muted">Nessuna offerta disponibile.</p>';
$('offers').innerHTML=cfg.offers.map((o,i)=>`<article class="card clickable" data-kind="offer" data-index="${i}" tabindex="0" role="button"><h4>${esc(o.title)}</h4><b class="price">${esc(o.pct)}</b><p class="muted">${esc(o.description||o.desc||'')}</p><p class="muted">Tocca per vedere i dettagli</p></article>`).join('')||'<p class="muted">Nessuna promozione disponibile.</p>'}
function handleCard(e){const c=e.target.closest('[data-kind]');if(!c)return;const i=+c.dataset.index,k=c.dataset.kind;if(k==='product')openDetail('Prodotto',cfg.products[i]);else if(k==='plan')openDetail('Telefonia / Fibra',cfg.plans[i]);else openDetail('Offerta',cfg.offers[i])}
$('products').onclick=$('plans').onclick=$('offers').onclick=handleCard;$('products').onkeydown=$('plans').onkeydown=$('offers').onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();handleCard(e)}};
$('detailClose').onclick=closeDetail;$('detailBackdrop').onclick=e=>{if(e.target===$('detailBackdrop'))closeDetail()};document.addEventListener('keydown',e=>{if(e.key==='Escape')closeDetail()});
function renderNews(a){if(!a?.length)return;$('novita').hidden=false;$('news').innerHTML=a.map(n=>`<article><h4>${esc(n.title)}</h4><p class="muted">${esc(n.description)}</p><button data-go="${esc(n.section)}">Vedi</button></article>`).join('')}
$('news').onclick=e=>{const s=e.target.dataset.go;if(s)location.hash=s};
async function init(){const r=await fetch('/api/config');if(!r.ok)throw Error('Impossibile caricare la configurazione');cfg=await r.json();$('shop').textContent=cfg.shopName||'FVC Project';$('contacts').textContent=[cfg.address,cfg.phone,cfg.whatsapp].filter(Boolean).join(' · ');[...new Set((cfg.products||[]).map(p=>p.brand).filter(Boolean))].sort().forEach(x=>$('brand').add(new Option(x,x)));render();renderNews(cfg.news)}
$('search').oninput=render;$('brand').onchange=render;init().catch(console.error);
$('push').onclick=async()=>{if(!('serviceWorker'in navigator)||!('PushManager'in window))return alert('Notifiche non supportate');const key=(await fetch('/api/vapid-public-key').then(r=>r.json())).publicKey;if(!key)return alert('Notifiche da configurare su Render');const p=await Notification.requestPermission();if(p!=='granted')return;const reg=await navigator.serviceWorker.ready;const bytes=Uint8Array.from(atob(key.replace(/-/g,'+').replace(/_/g,'/')),c=>c.charCodeAt(0));const sub=await reg.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:bytes});await fetch('/api/subscribe',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(sub)});$('push').textContent='Notifiche attive ✓'};
if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js');
</script></body></html>